// Setup (run FIRST): scripts/self-update-1216-setup.sh
// Teardown (always): scripts/self-update-1216-teardown.sh
//
// A5 — on-device self-update, end to end through the REAL `mobissh/updates`
// channel (#1216, spec docs/self-update.md R8-R11).
//
// The manifest + APK are served by an in-process http MockClient (the network
// is not what is under test; the device's PackageManager is), through the real
// checker → banner → installer → Kotlin verify → installer hand-off. Three
// builds are offered in turn:
//
//   1. FOREIGN PACKAGE (com.flavordrake.notmobissh) → R10 refuses on the
//      package name; the downloaded file is gone.
//   2. FOREIGN KEY (com.flavordrake.mobissh signed by a throwaway key) → R10
//      refuses on the signing certificate; the file is gone. Its sha256 DOES
//      match the manifest: this is exactly the "host is compromised" case the
//      sha alone cannot catch.
//   3. OUR OWN APK (this test app's base.apk: same package, same key) → R10
//      accepts and the hand-off reaches the SYSTEM PACKAGE INSTALLER: the
//      intent resolves to a package installer and this activity leaves the
//      resumed state because the installer screen took the foreground. The
//      teardown records the resumed activity + a screenshot as evidence.
//
// The two foreign stubs are committed bytes
// (fixtures/self_update_apks.dart, regenerated by
// scripts/gen-self-update-fixture-apks.sh). The setup script keeps the
// "install unknown apps" appop granted, which a test cannot toggle itself.
//
// Run: EMU_LEASE_WAIT=3600 scripts/with-fleet-emulator.sh -- \
//        scripts/integration-subset.sh integration_test/self_update_1216_test.dart
// No SSH session is needed — this test never connects.

import 'dart:convert';
import 'dart:io';

import 'package:cryptography/cryptography.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:integration_test/integration_test.dart';

import 'package:mobissh/services/self_update.dart';
import 'package:mobissh/state/update_providers.dart';
import 'package:mobissh/ui/update_banner.dart';

import 'fixtures/self_update_apks.dart';

const String host = 'https://mobissh.tailbe5094.ts.net';

class _LifecycleLog with WidgetsBindingObserver {
  final List<AppLifecycleState> states = <AppLifecycleState>[];
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) => states.add(state);
}

Future<String> _sha256Hex(List<int> bytes) async {
  final d = await Sha256().hash(bytes);
  return d.bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
}

/// This test app's own installed APK — mapped into our process, so readable.
File _ownBaseApk() {
  for (final line in File('/proc/self/maps').readAsLinesSync()) {
    final path = line.split(RegExp(r'\s+')).last;
    if (path.endsWith('/base.apk') && path.contains('com.flavordrake.mobissh')) {
      return File(path);
    }
  }
  throw StateError('base.apk not found in /proc/self/maps');
}

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets(
    'A5: foreign package + foreign key refused (R10); own APK reaches the '
    'system installer (R11)',
    (tester) async {
      await tester.pumpWidget(const SizedBox.shrink());
      await tester.pump(const Duration(milliseconds: 300));

      const platform = ChannelUpdatePlatform();
      final caps = await platform.capabilities();
      debugPrint('A5 capabilities supported=${caps.supported} abi=${caps.abi}');
      expect(caps.supported, isTrue,
          reason: 'the debug (sideload) manifest must carry the updater '
              'provider + REQUEST_INSTALL_PACKAGES (R13 keeps them out of '
              'Play only)');
      expect(caps.abi, isNotEmpty);
      final updatesDir = await platform.updatesDir();

      // What the mock host serves right now.
      var servedBuild = 0;
      List<int> servedApk = const <int>[];
      var servedSha = '';
      final client = MockClient.streaming((req, _) async {
        if (req.url.path == '/android-latest.json') {
          final body = utf8.encode(jsonEncode(<String, Object?>{
            'version': '9.9.9-fixture+$servedBuild',
            'build': servedBuild,
            'abi': caps.abi,
            'url': '$host/fixture-$servedBuild.apk',
            'sha256': servedSha,
            'builtAt': '2026-09-27T00:00:00Z',
            'notes': 'A5 fixture',
          }));
          return http.StreamedResponse(Stream.value(body), 200,
              contentLength: body.length);
        }
        if (req.url.path == '/fixture-$servedBuild.apk') {
          const chunk = 1024 * 1024;
          final chunks = <List<int>>[
            for (var i = 0; i < servedApk.length; i += chunk)
              servedApk.sublist(i, (i + chunk).clamp(0, servedApk.length)),
          ];
          return http.StreamedResponse(Stream.fromIterable(chunks), 200,
              contentLength: servedApk.length);
        }
        return http.StreamedResponse(const Stream.empty(), 404);
      });

      final container = ProviderContainer(overrides: [
        updateHttpClientProvider.overrideWithValue(client),
        runningBuildProvider.overrideWithValue(1),
      ]);
      addTearDown(container.dispose);

      await tester.pumpWidget(UncontrolledProviderScope(
        container: container,
        child: const MaterialApp(
          home: Scaffold(
            body: Column(children: [UpdateBanner(), UpdateSettingsSection()]),
          ),
        ),
      ));

      Future<void> pumpUntil(bool Function() done, String what,
          {Duration timeout = const Duration(seconds: 90)}) async {
        final end = DateTime.now().add(timeout);
        while (!done()) {
          if (DateTime.now().isAfter(end)) fail('timed out waiting for $what');
          // Real time, not the test clock: the work is platform I/O. And no
          // pump once the installer has the foreground — a paused engine
          // produces no frame for pump() to await.
          await Future<void>.delayed(const Duration(milliseconds: 200));
          if (WidgetsBinding.instance.lifecycleState ==
              AppLifecycleState.resumed) {
            await tester.pump();
          }
        }
      }

      List<String> apksLeft() => updatesDir.existsSync()
          ? updatesDir
              .listSync()
              .map((e) => e.uri.pathSegments.last)
              .where((n) => n.endsWith('.apk'))
              .toList()
          : const <String>[];

      Future<UpdateProgress> offerAndInstall(int build, List<int> apk) async {
        servedBuild = build;
        servedApk = apk;
        servedSha = await _sha256Hex(apk);
        container.invalidate(updateCheckProvider);
        await pumpUntil(
          () => find
              .textContaining('9.9.9-fixture+$build')
              .evaluate()
              .isNotEmpty,
          'banner offering build $build',
        );
        expect(find.byKey(const Key('update-banner')), findsOneWidget);
        await tester.tap(find.byKey(const Key('update-install')));
        await tester.pump();
        await pumpUntil(() {
          final p = container.read(updateDownloadProvider);
          return p.stage != UpdateStage.idle && !p.isBusy;
        }, 'install of build $build to finish');
        final p = container.read(updateDownloadProvider);
        debugPrint('A5 build $build -> ${p.stage} "${p.message}" '
            'installer=${p.installer}');
        return p;
      }

      // 1. Foreign PACKAGE.
      final pkg = await offerAndInstall(
          1001, base64Decode(foreignPackageApkBase64));
      expect(pkg.stage, UpdateStage.failed);
      expect(pkg.message, contains('package com.flavordrake.notmobissh'));
      expect(apksLeft(), isEmpty, reason: 'R10 refusal must delete the file');
      expect(find.byKey(const Key('update-message')), findsWidgets);

      // 2. Foreign KEY, same package — sha256 matches the manifest.
      final key =
          await offerAndInstall(1002, base64Decode(foreignKeyApkBase64));
      expect(key.stage, UpdateStage.failed);
      expect(key.message, contains('signing certificate'));
      expect(apksLeft(), isEmpty, reason: 'R10 refusal must delete the file');

      // 3. Our own APK → the system installer.
      final lifecycle = _LifecycleLog();
      WidgetsBinding.instance.addObserver(lifecycle);
      addTearDown(() => WidgetsBinding.instance.removeObserver(lifecycle));
      final own = _ownBaseApk();
      debugPrint('A5 own APK ${own.path} (${own.lengthSync()} bytes)');
      final ok = await offerAndInstall(1003, own.readAsBytesSync());
      expect(ok.stage, UpdateStage.handedOff,
          reason: 'needsPermission here means the setup appop grant did not '
              'land; failed means R10 refused our own APK: ${ok.message}');
      expect(ok.installer, contains('packageinstaller'),
          reason: 'the ACTION_VIEW apk intent must resolve to the system '
              'package installer');
      await pumpUntil(
        // The Google package installer is a DIALOG activity over ours, so we
        // go `inactive` (still visible behind it), not paused — measured on
        // the fleet emulator; the setup watcher records the dialog itself.
        () => lifecycle.states.any((s) =>
            s == AppLifecycleState.inactive ||
            s == AppLifecycleState.hidden ||
            s == AppLifecycleState.paused),
        'the installer screen to take the foreground',
        timeout: const Duration(seconds: 20),
      );
      // Hold the installer on screen long enough for the setup script's
      // watcher (1s poll) to record it as evidence.
      await Future<void>.delayed(const Duration(seconds: 4));
      debugPrint('A5 lifecycle after hand-off: ${lifecycle.states}');
      // The accepted file stays for the installer to read (R12 removes it on
      // the next launch).
      expect(apksLeft(), contains('mobissh-update-1003.apk'));
    },
    timeout: const Timeout(Duration(minutes: 8)),
  );
}
