#!/usr/bin/env bash
# scripts/gen-self-update-fixture-apks.sh — regenerate the two FOREIGN stub APKs
# the #1216 on-device test (integration_test/self_update_1216_test.dart) feeds
# to the R10 check, and write them as base64 into
# native/integration_test/fixtures/self_update_apks.dart.
#
#   foreignKeyApk      package com.flavordrake.mobissh, signed by a throwaway
#                      key → must be refused on the SIGNING CERTIFICATE
#   foreignPackageApk  package com.flavordrake.notmobissh, throwaway key →
#                      must be refused on the PACKAGE NAME (checked first)
#
# WHY committed bytes instead of a per-run setup step: the test then needs no
# device push, no SELinux question about /data/local/tmp, and no host tools at
# test time. The stubs are ~3KB (manifest only, hasCode=false). The throwaway
# keystore lives in a temp dir and is deleted — it signs nothing real.
#
# Needs the Android SDK build-tools (aapt2, apksigner) + keytool. Exit 0 = written.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SDK=""
for c in "${ANDROID_SDK_ROOT:-}" "${ANDROID_HOME:-}" /opt/android-sdk; do
  if [[ -n "$c" && -d "${c}/build-tools" ]]; then SDK="$c"; break; fi
done
if [[ -z "$SDK" ]]; then
  echo "! no Android SDK with build-tools found" >&2
  exit 2
fi
BT="$(ls -d "${SDK}"/build-tools/* | sort -V | tail -n 1)"
PLATFORM="$(ls -d "${SDK}"/platforms/android-* | sort -V | tail -n 1)"
OUT="${REPO_ROOT}/native/integration_test/fixtures/self_update_apks.dart"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "> build-tools: ${BT}"
echo "> platform:    ${PLATFORM}"

keytool -genkeypair -keystore "${WORK}/throwaway.jks" -storepass fixture \
  -keypass fixture -alias fixture -keyalg RSA -keysize 2048 -validity 3650 \
  -dname "CN=mobissh self-update fixture (NOT a release key)"

stub() {
  local name="$1" package="$2"
  cat >"${WORK}/${name}.xml" <<EOF
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${package}" android:versionCode="999999" android:versionName="fixture">
    <application android:label="fixture" android:hasCode="false"/>
</manifest>
EOF
  "${BT}/aapt2" link --manifest "${WORK}/${name}.xml" \
    -I "${PLATFORM}/android.jar" -o "${WORK}/${name}-unsigned.apk"
  "${BT}/zipalign" -f 4 "${WORK}/${name}-unsigned.apk" "${WORK}/${name}-aligned.apk"
  "${BT}/apksigner" sign --ks "${WORK}/throwaway.jks" --ks-pass pass:fixture \
    --key-pass pass:fixture --out "${WORK}/${name}.apk" "${WORK}/${name}-aligned.apk"
  "${BT}/apksigner" verify "${WORK}/${name}.apk"
}

stub foreign-key com.flavordrake.mobissh
stub foreign-package com.flavordrake.notmobissh

{
  echo "// GENERATED by scripts/gen-self-update-fixture-apks.sh — do not edit."
  echo "// Foreign stub APKs for the #1216 R10 on-device test. Signed by a"
  echo "// throwaway key that was deleted after signing; not a release artifact."
  echo "// ignore_for_file: lines_longer_than_80_chars"
  echo ""
  echo "/// package com.flavordrake.mobissh, FOREIGN signing key."
  echo "const String foreignKeyApkBase64 ="
  echo "    '$(base64 -w 0 "${WORK}/foreign-key.apk")';"
  echo ""
  echo "/// package com.flavordrake.notmobissh (foreign key too)."
  echo "const String foreignPackageApkBase64 ="
  echo "    '$(base64 -w 0 "${WORK}/foreign-package.apk")';"
} >"$OUT"

echo "+ wrote ${OUT} ($(wc -c <"$OUT") bytes)"
