#!/usr/bin/env bash
# scripts/paint-replay.sh — replay a recorded bug-report byte-trace through the
# REAL paint stack on the emulator (paint replay harness).
#
# Regenerates the embedded fixture the on-device test compiles in
# (native/integration_test/fixtures/paint_replay_fixture.dart) from a
# bug-report byte-trace JSON, then runs the emulator integration test
# (integration_test/paint_replay_test.dart) over the standard
# native-connect-test.sh bridge. The test mounts the real GhosttyTerminalView,
# injects the trace's chunks through the SAME proxy.output seam live SSH bytes
# use, and asserts (a) the final VT state is RENDERED on the grid and (b) the
# paint-stack boundary counters advanced (bytes → notifies → paints).
#
# Usage:
#   scripts/paint-replay.sh                      # replay the committed default
#                                                # (owner 2026-07-08T00-51-01)
#   scripts/paint-replay.sh path/to/trace.json   # replay any captured trace
#   GEN_ONLY=1 scripts/paint-replay.sh t.json    # regenerate fixture, no run
#
# NOTE: replaying a NON-default trace rewrites the generated fixture file in
# the working tree. Restore it (git checkout -- native/integration_test/
# fixtures/paint_replay_fixture.dart) before committing unless the new trace
# should become the pinned regression input.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOBISSH_TMPDIR="${MOBISSH_TMPDIR:-/tmp/mobissh}"
MOBISSH_LOGDIR="${MOBISSH_LOGDIR:-/tmp/mobissh/logs}"
mkdir -p "$MOBISSH_TMPDIR" "$MOBISSH_LOGDIR"
LOGFILE="${MOBISSH_LOGDIR}/paint-replay.log"
exec > >(tee -a "$LOGFILE") 2>&1

DEFAULT_TRACE="${REPO_ROOT}/native/test/fixtures/replay/psreadline_stale_paint_66x34.byte-trace.json"
TRACE_JSON="${1:-$DEFAULT_TRACE}"
FIXTURE_DART="${REPO_ROOT}/native/integration_test/fixtures/paint_replay_fixture.dart"

if [[ ! -f "$TRACE_JSON" ]]; then
  echo "! trace not found: $TRACE_JSON"
  exit 2
fi

echo "> generating embedded fixture from: $TRACE_JSON"
python3 - "$TRACE_JSON" "$FIXTURE_DART" <<'PYEOF'
import base64, json, sys, os

trace_path, out_path = sys.argv[1], sys.argv[2]
raw = open(trace_path, 'rb').read()
# Validate it parses and carries the expected shape before embedding.
doc = json.loads(raw)
assert 'byteTrace' in doc and 'grid' in doc, 'not a bug-report byte-trace JSON'
b64 = base64.b64encode(raw).decode('ascii')
lines = [b64[i:i+76] for i in range(0, len(b64), 76)]
body = "'\n    '".join(lines)
src = os.path.basename(trace_path)
events = len(doc['byteTrace'])
grid = doc['grid']
with open(out_path, 'w') as f:
    f.write(f"""// GENERATED by scripts/paint-replay.sh — do not edit by hand.
//
// Embedded bug-report byte-trace for the on-device paint replay test
// (integration_test/paint_replay_test.dart). The emulator cannot read repo
// files, so the trace JSON is compiled in as base64 and decoded at runtime by
// `paintReplayFixtureJson`.
//
// Source: {src}
// Events: {events}, captured grid: {grid['cols']}x{grid['rows']}

import 'dart:convert';

/// Base64 of the raw bug-report byte-trace JSON.
const String kPaintReplayFixtureB64 =
    '{body}';

/// The trace JSON, decoded. Feed to `parseByteTrace(...)`.
String paintReplayFixtureJson() =>
    utf8.decode(base64Decode(kPaintReplayFixtureB64));
""")
print(f"> wrote {out_path} ({events} events, grid {grid['cols']}x{grid['rows']})")
PYEOF

if [[ "${GEN_ONLY:-0}" == "1" ]]; then
  echo "> GEN_ONLY=1 — fixture regenerated, skipping the emulator run"
  exit 0
fi

exec "${REPO_ROOT}/scripts/native-connect-test.sh" integration_test/paint_replay_test.dart
