/**
 * Red baseline for issue #499 — client-side forwards state machine.
 *
 * Covers:
 *   B1   openLocalForward sends fwd_local_listen and resolves on fwd_local_ready
 *   B7   closeLocalForward sends fwd_local_close; removes entry on fwd_local_closed
 *   EC5  Independent forwards do not cross-affect (failure on F1 does not
 *        touch F2's entry or listening port; the client routes by `id`)
 *
 * Pre-implementation: src/modules/forwards.ts is missing → tests fail on
 * import. Acceptable red baseline.
 *
 * NOTE: openLocalForward/closeLocalForward likely pull the active session's
 * WebSocket from appState (mirroring sendSSHInput). To keep the test loose
 * about WHICH session API the implementation picks, we inject a fake WS via
 * the module's documented test seam — `setActiveWsForTesting` — which the
 * implementation must export.
 */

import { describe, it, expect, beforeEach, vi, afterEach } from 'vitest';
import type { LocalForward, ClientMessage, ServerMessage } from '../types.js';

vi.stubGlobal('localStorage', {
  getItem: () => null,
  setItem: () => {},
  removeItem: () => {},
  clear: () => {},
  length: 0,
  key: () => null,
});
vi.stubGlobal('location', { hostname: 'localhost' });

/**
 * A minimal stand-in for a WebSocket that captures outbound frames and lets
 * the test drive inbound frames back into the module.
 */
class FakeWs {
  public sent: string[] = [];
  public readyState = 1; // OPEN
  send(data: string): void {
    this.sent.push(data);
  }
  // Inbound frames are routed via the module's handleServerForwardMessage().
  parseSent(): ClientMessage[] {
    return this.sent.map((s) => JSON.parse(s) as ClientMessage);
  }
}

describe('forwards: openLocalForward / closeLocalForward (#499)', () => {
  let fakeWs: FakeWs;

  beforeEach(() => {
    vi.resetModules();
    fakeWs = new FakeWs();
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    // Reinstate the basic globals between tests
    vi.stubGlobal('localStorage', {
      getItem: () => null, setItem: () => {}, removeItem: () => {},
      clear: () => {}, length: 0, key: () => null,
    });
    vi.stubGlobal('location', { hostname: 'localhost' });
  });

  it('B1: openLocalForward(srcPort, dstHost, dstPort) sends exactly one fwd_local_listen frame', async () => {
    const { openLocalForward, setActiveWsForTesting } = await import('../forwards.js');
    setActiveWsForTesting(fakeWs as unknown as WebSocket);

    // Kick off the open; don't await — we want to assert the frame fired
    // before the server reply arrives.
    void openLocalForward(8080, 'example.internal', 80);

    expect(fakeWs.sent.length).toBe(1);
    const msg = JSON.parse(fakeWs.sent[0]!) as ClientMessage;
    expect(msg.type).toBe('fwd_local_listen');
    if (msg.type !== 'fwd_local_listen') throw new Error('unreachable');
    expect(msg.srcPort).toBe(8080);
    expect(msg.dstHost).toBe('example.internal');
    expect(msg.dstPort).toBe(80);
    expect(typeof msg.id).toBe('string');
    expect(msg.id.length).toBeGreaterThan(0);
  });

  it('B1b: openLocalForward returns a Promise that resolves on fwd_local_ready', async () => {
    const { openLocalForward, handleServerForwardMessage, setActiveWsForTesting } =
      await import('../forwards.js');
    setActiveWsForTesting(fakeWs as unknown as WebSocket);

    const pending: Promise<LocalForward> = openLocalForward(0, 'host', 22);
    const sent = fakeWs.parseSent();
    const listenMsg = sent[0]!;
    if (listenMsg.type !== 'fwd_local_listen') throw new Error('unreachable');
    const id = listenMsg.id;

    // Drive ready back into the module
    const ready: ServerMessage = {
      type: 'fwd_local_ready',
      id,
      srcPort: 49152,    // OS-assigned ephemeral (EC6 case)
      listenAddr: '127.0.0.1',
    };
    handleServerForwardMessage(ready);

    const fwd = await pending;
    expect(fwd.id).toBe(id);
    expect(fwd.srcPort).toBe(49152);
    expect(fwd.listenAddr).toBe('127.0.0.1');
    expect(fwd.state).toBe('active');
    expect(typeof fwd.openedAt).toBe('number');
  });

  it('B1c: ids generated by openLocalForward are unique across calls', async () => {
    const { openLocalForward, setActiveWsForTesting } = await import('../forwards.js');
    setActiveWsForTesting(fakeWs as unknown as WebSocket);

    void openLocalForward(8080, 'a', 80);
    void openLocalForward(8081, 'b', 80);
    void openLocalForward(8082, 'c', 80);

    const ids = fakeWs.parseSent()
      .filter((m): m is Extract<ClientMessage, { type: 'fwd_local_listen' }> => m.type === 'fwd_local_listen')
      .map((m) => m.id);
    expect(ids.length).toBe(3);
    expect(new Set(ids).size).toBe(3);
  });

  it('B7: closeLocalForward(id) sends fwd_local_close and removes entry on fwd_local_closed', async () => {
    const { openLocalForward, closeLocalForward, handleServerForwardMessage, listForwards, setActiveWsForTesting } =
      await import('../forwards.js');
    setActiveWsForTesting(fakeWs as unknown as WebSocket);

    // Open + activate one forward
    const opening = openLocalForward(8080, 'host-a', 80);
    const listenMsg = fakeWs.parseSent()[0]!;
    if (listenMsg.type !== 'fwd_local_listen') throw new Error('unreachable');
    const id = listenMsg.id;
    handleServerForwardMessage({
      type: 'fwd_local_ready', id, srcPort: 8080, listenAddr: '127.0.0.1',
    });
    await opening;

    expect(listForwards().length).toBe(1);

    // Now close
    fakeWs.sent.length = 0; // reset to only see the close frame
    void closeLocalForward(id);

    expect(fakeWs.sent.length).toBe(1);
    const closeMsg = JSON.parse(fakeWs.sent[0]!) as ClientMessage;
    expect(closeMsg.type).toBe('fwd_local_close');
    if (closeMsg.type !== 'fwd_local_close') throw new Error('unreachable');
    expect(closeMsg.id).toBe(id);

    // Driving the server's fwd_local_closed removes the entry
    handleServerForwardMessage({ type: 'fwd_local_closed', id, reason: 'user' });
    expect(listForwards().length).toBe(0);
  });

  it('EC5: failure on F1 does not affect F2', async () => {
    const { openLocalForward, handleServerForwardMessage, listForwards, setActiveWsForTesting } =
      await import('../forwards.js');
    setActiveWsForTesting(fakeWs as unknown as WebSocket);

    // Open F1 and F2 concurrently
    const p1 = openLocalForward(8080, 'a', 80);
    const p2 = openLocalForward(9090, 'b', 80);

    const sent = fakeWs.parseSent()
      .filter((m): m is Extract<ClientMessage, { type: 'fwd_local_listen' }> => m.type === 'fwd_local_listen');
    expect(sent.length).toBe(2);
    const [m1, m2] = sent;
    const id1 = m1!.id;
    const id2 = m2!.id;

    // Activate both
    handleServerForwardMessage({ type: 'fwd_local_ready', id: id1, srcPort: 8080, listenAddr: '127.0.0.1' });
    handleServerForwardMessage({ type: 'fwd_local_ready', id: id2, srcPort: 9090, listenAddr: '127.0.0.1' });
    await Promise.all([p1, p2]);

    // F1 errors out
    handleServerForwardMessage({
      type: 'fwd_local_error', id: id1, code: 'forward_failed', message: 'target unreachable',
    });
    handleServerForwardMessage({ type: 'fwd_local_closed', id: id1, reason: 'forward_failed' });

    // F2 must still be in the list and unchanged
    const list = listForwards();
    expect(list.find((f) => f.id === id1)).toBeUndefined();
    const f2 = list.find((f) => f.id === id2);
    expect(f2).toBeDefined();
    expect(f2!.srcPort).toBe(9090);
    expect(f2!.state).toBe('active');
  });
});
